import { z } from "zod";
import { FirestoreTimestamp } from "@/lib/helpers/firestore-timestamp";


export const EventRecordSchema = z.object({
  id: z.string().optional(), // ID will be generated by Firestore, so it's optional on input
  name: z.string().min(1),
  slug: z.string().min(1),
  details: z.string().min(1),
  imageUrl: z.string().min(1),
  date: FirestoreTimestamp,
});

export const ParticipantRecordSchema = z.object({
  id: z.string().optional(), 
  name: z.string().min(1),
  email: z.email(),
  eventid: z.string().min(1),
  joinedAt: FirestoreTimestamp,
});


export const EventParticipantSchema = z.object({
  id: z.string().optional(), 
  eventId: z.string().min(1),
  eventslug:z.string().min(1),
  participantId: z.string().min(1),
  joinedAt: z.date(), 
});



export type EventParticipant = z.infer<typeof EventParticipantSchema>;
export type EventRecord = z.infer<typeof EventRecordSchema>;
export type ParticipantRecord = z.infer<typeof ParticipantRecordSchema>;
