import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { AuthProvider } from "@/utils/auth-provider";
import { ourFileRouter } from "./api/uploadthing/core";
import Header from "@/components/ui/header";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CDG Website",
  description: "Generated by create next app",
  icons: {
    icon: "/logo_1.svg",
    shortcut: "/logo_1.svg",
    apple: "/logo_1.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} no-scrollbar`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased no-scrollbar`}
      >
        <AuthProvider>
          <div className="min-h-screen bg-background text-foreground">
            <Header />
            {children}
          </div>
        </AuthProvider>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
      </body>
    </html>
  );
}
